language: java

jdk:
  - oraclejdk8

before_script:
  - mongod --version

services:
  - mongodb

env:
  matrix:
    - PROFILE=ci
    - PROFILE=mongo36-next

# Current MongoDB version is 2.4.2 as of 2016-04, see https://github.com/travis-ci/travis-ci/issues/3694
# apt-get starts a MongoDB instance so it's not started using before_script
addons:
  apt:
    sources:
      - mongodb-3.4-precise
    packages:
    - mongodb-org-server
    - mongodb-org-shell
    - oracle-java8-installer

sudo: false

cache:
  directories:
    - $HOME/.m2

install: true

script: "mvn clean dependency:list test -P${PROFILE} -Dsort"
