name: CI Build

on:
  workflow_dispatch: 
  push:
#    branches: [ main, 5.0.x, 4.5.x, 'issue/**' ]
    branches: [ 'issue/actions' ]

permissions: read-all

jobs:
  build-java:
    strategy:
      matrix:
        java-version: [ base, main ]
        mongo-version: [8.0]
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java and Maven
        uses: spring-projects/spring-data-release/actions/setup-maven@main
        with:
          java-version: ${{ matrix.java-version }}
          develocity-access-key: '${{ secrets.DEVELOCITY_ACCESS_KEY }}'
      - name: Mongo Version
        id: determine-mongo-version
        uses: ./.github/actions/managed-version
        with:
          managed-versions: ${CONFIG_JSON}
          key: '.database.mongodb'
          version: '${{ matrix.mongo-version }}'
      - name: Initialize MongoDB
        uses: ./.github/actions/mongodb/
        with:
          mongo-version: ${{ steps.determine-mongo-version.outputs.managed-version }}
          replica-set: 'rs0'
      - name: Build
        uses: spring-projects/spring-data-release/actions/maven-build@main
        with:
          run: ./mvnw -Dsort -B -U -Pci clean dependency:list verify
